### ISSUE TITLE
Cambio de arquitectura

### ISSUE THREAD

**Issue by ernestoalejo** [ernestoalejo/virtual-vulcano#45]
Tenemos que ver que opciones tenemos y que podemos elegir sabiendo el nuevo funcionamiento de etcd y coreos. @santiagopuerta tiene una propuesta. También añado yo a la discusión que si añadimos cualquier tipo de monitorización al producto final estaremos cumpliendo con los objetivos de DAI que también son importantes.

**Comment by ernestoalejo** [comment]
Dejo como referencia la página que usaremos para controlar systemd y fleetctl desde el contenedor de la aplicación: https://groups.google.com/forum/#!topic/coreos-dev/AXCs_2_J6Mc

**Comment by albertomoreno** [comment]
A mi me parece buena idea añadir monitorizacion a la aplicación. Ademas de cumplir objetivos, puede resultar bastante util para el usuario.

**Comment by santiagopuerta** [comment]
Me parece una gran idea @ernestoalejo. Yo he pensado que podríamos añadir en la interfaz web un botón para automatizar la creación de un apache en una instancia, un mysql en otra y que montase un wordpress, drupal, etc... usando estos dos, o bien que nos lo generase todo en una.

**Comment by ernestoalejo** [comment]
One-Click installer como lo suelen llamar en wix, cpanel y varios

**Comment by yonatan24891** [comment]
Me parece una buena idea, así añadimos funcionalidad a la aplicación

**Comment by albertomoreno** [comment]
En lugar de usar mysql, ¿se podria usar mongodb o sería demasiado pesado para usarlo en maquinas pequeñas? 
¿Cuantas maquinas podrá tener un usuario que utilice la aplicación, una o varias maquinas a la vez?

**Comment by santiagopuerta** [comment]
Vamos a necesitar instalar mysql para poder instalar wordpress, drupal, ...
¿Podríamos tener dos o tres máquinas como mucho no?.

**Comment by ernestoalejo** [comment]
Vamos a ir con la instalación de CMS y su monitorización de forma rápida.
