### ISSUE TITLE
Bootstrap y expressjs para DAI

### ISSUE THREAD

**Issue by santiagopuerta** [ernestoalejo/virtual-vulcano#46]
El otro día nos comentaron que podíamos usar cualquier framework y bootstrap para la ultima practica de DAI.
Pero no se hasta donde es necesario llegar para cumplir con esta ultima práctica. ¿Alguno de vosotros: @ernestoalejo @albertomoreno @yonatan24891 sabe si con lo que tenemos es suficiente o es necesario cumplir con algún mínimo de funcionalidad web?.

**Comment by albertomoreno** [comment]
En un documento que subio hace tiempo indicando que la ultima practica se hacia en grupo, solo pone lo que estas diciendo tu @santiagopuerta.

**Comment by yonatan24891** [comment]
Yo creo que si, lo podemos poner un poco más bonito pero con bootstrap+express creo que hay suficiente

**Comment by albertomoreno** [comment]
Si estamos todos de acuerdo, usamos Bootstrap y expressjs.
