### ISSUE TITLE
Inicializar la base de datos

### ISSUE THREAD

**Issue by albertomoreno** [ernestoalejo/virtual-vulcano#48]

**Comment by yonatan24891** [comment]
@santiagopuerta está esto acabado ya?

**Comment by santiagopuerta** [comment]
No, no esta terminado. Esto es para crear tablas donde este el usuario Root, etc...

**Comment by ernestoalejo** [comment]
Asignando a @santiagopuerta que se estaba ocupando del primer usuario root de la aplicación. En cuanto esté listo se cierra la issue.
