### ISSUE TITLE
Poner licencia a todos los archivos

### ISSUE THREAD

**Issue by yonatan24891** [ernestoalejo/virtual-vulcano#52]
Recordad poner la licencia en la cabecera de cada fichero

**Comment by yonatan24891** [comment]
Acordaros que estamos ya en el 2015 a lahora de poner la licencia xD

**Comment by santiagopuerta** [comment]
Si, seguro que olvidamos algún fichero sin ponerle la licencia.

**Comment by yonatan24891** [comment]
Añadidos en el commit 90438050431ccf4cc6b8dffdc12b8f12a13ed01e
