### ISSUE TITLE
Aumentar RAM

### ISSUE THREAD

**Issue by yonatan24891** [ernestoalejo/virtual-vulcano#59]
Deberíamos aumentar la ram de la máquina en Azure porque se me queda pillada al crear los contenedores, ¿Que opináis?

**Comment by santiagopuerta** [comment]
He aumentado la ram en el servidor a 2GB porque a mi también se me quedaba bloqueado el terminal al iniciar  los contenedores.

**Comment by albertomoreno** [comment]
Está bien porque tambien se me habia quedado bloqueado.
