### ISSUE TITLE
Sesiones

### ISSUE THREAD

**Issue by albertomoreno** [ernestoalejo/virtual-vulcano#60]

**Comment by santiagopuerta** [comment]
Voy a ponerme con las sesiones. Yo las creo.

**Comment by albertomoreno** [comment]
@santiagopuerta ya se han terminado las sesiones?

**Comment by santiagopuerta** [comment]
@albertomoreno Estoy realizando pruebas. Lo tengo casi listo.

**Comment by ernestoalejo** [comment]
@santiagopuerta Están ya las pruebas funcionando no?

**Comment by santiagopuerta** [comment]
Funcionando y todo correcto. Añadido en https://github.com/ernestoalejo/virtual-vulcano/commit/3cdaec4a3c10ab83d943a660ac622f7f62b89c4c
