### ISSUE TITLE
Haproxy

### ISSUE THREAD

**Issue by ernestoalejo** [ernestoalejo/virtual-vulcano#61]

**Comment by yonatan24891** [comment]
Falta acabar el archivo de configuración

**Comment by santiagopuerta** [comment]
@yonatan24891 esto, está terminado ya no?

**Comment by yonatan24891** [comment]
Creo que alguien lo termino, haber que opina @ernestoalejo

**Comment by ernestoalejo** [comment]
Se va a hacer para que funcione así que cierro
