### ISSUE TITLE
Eliminar antiguos scripts y usar vagrant para todo

### ISSUE THREAD

**Issue by ernestoalejo** [ernestoalejo/virtual-vulcano#62]

**Comment by ernestoalejo** [comment]
Asignando a Alberto porque ha hecho poco de máquinas

**Comment by santiagopuerta** [comment]
¿Pero al final vamos a usar vagrant?

**Comment by ernestoalejo** [comment]
Yeah: https://github.com/ernestoalejo/virtual-vulcano/blob/master/Vagrantfile

**Comment by ernestoalejo** [comment]
¿Cómo vamos con esto Santi?

**Comment by santiagopuerta** [comment]
Added in https://github.com/ernestoalejo/virtual-vulcano/commit/af95af530cdc753ebb5eef25db5b8ded91534f84
