### ISSUE TITLE
Iconos de font awesome.

### ISSUE THREAD

**Issue by santiagopuerta** [ernestoalejo/virtual-vulcano#63]
Podríamos usar los iconos de [font awesome](http://fortawesome.github.io/Font-Awesome/) para el panel de administración.

**Comment by albertomoreno** [comment]
Lo asigno a @yonatan24891 que esta con el diseño y ha hecho menos en la parte de la web.

**Comment by yonatan24891** [comment]
Ya están los iconos colocados
