### ISSUE TITLE
Montarlo en azure

### ISSUE THREAD

**Issue by santiagopuerta** [ernestoalejo/virtual-vulcano#72]

**Comment by albertomoreno** [comment]
El script deberia de estar listo, hay que crear la maquina y probarlo

**Comment by yonatan24891** [comment]
Hay que hacerlo ya que la entrega es para hoy

**Comment by santiagopuerta** [comment]
Si, lo acabo de poner en azure y para descargar los contenedores tarda lo suyo.

**Comment by ernestoalejo** [comment]
Vamos a montarlo sobre Digital Ocean y ya me encargo yo
