### ISSUE TITLE
Terminar los test

### ISSUE THREAD

**Issue by santiagopuerta** [ernestoalejo/virtual-vulcano#73]

**Comment by albertomoreno** [comment]
Yo ya he terminado el test del manejador que muestra el formulario de cambiar contraseña

**Comment by yonatan24891** [comment]
Yo ya he terminado el de los plugins

**Comment by santiagopuerta** [comment]
Yo también he terminado los test de dashboard.

**Comment by ernestoalejo** [comment]
Los tests principales ya están preparados
