### ISSUE TITLE
Scripts de provisionamiento

### ISSUE THREAD

**Issue by albertomoreno** [ernestoalejo/virtual-vulcano#74]

**Comment by santiagopuerta** [comment]
Yo ya he terminado el de phpMyAdmin

**Comment by albertomoreno** [comment]
Yo he hecho los necesarios para que funcione el contenedor de haproxy.

**Comment by yonatan24891** [comment]
Yo todo lo que tiene que ver con el servicio FTP

**Comment by ernestoalejo** [comment]
Están funcionando así que se cierra
