### ISSUE TITLE
Integración continua (travis)

### ISSUE THREAD

**Issue by yonatan24891** [ernestoalejo/virtual-vulcano#75]
Abro este hilo, para comentar la integración continua que vamos a hacer con travis

**Comment by santiagopuerta** [comment]
Ya configuré lo de travis, pero se pueden añadir los nuevos test.

**Comment by albertomoreno** [comment]
He hecho unos tests para integracion continua.

**Comment by yonatan24891** [comment]
Yo también hice un test nuevo

**Comment by ernestoalejo** [comment]
En principio están ya hechos y funcionando por lo que veo: https://travis-ci.org/ernestoalejo/virtual-vulcano
