### ISSUE TITLE
Avisar al profesor de que vamos a ir a la presentación

### ISSUE THREAD

**Issue by ernestoalejo** [ernestoalejo/virtual-vulcano#78]
Que en principio vamos a ir, ¿no?

**Comment by yonatan24891** [comment]
Si, y habría que avisar al de DAI también

**Comment by santiagopuerta** [comment]
Si, al final vamos a quedar para el día 11 ¿verdad?.

**Comment by yonatan24891** [comment]
Si, porque el 10 no podemos con el examen de SPSI

**Comment by albertomoreno** [comment]
A mi me viene mejor el 11 tambien

**Comment by ernestoalejo** [comment]
Esperando a que conteste el profesor de DAI
