### ISSUE TITLE
Hacer funcionar Haproxy

### ISSUE THREAD

**Issue by albertomoreno** [ernestoalejo/virtual-vulcano#82]

**Comment by ernestoalejo** [comment]
![2843160](https://cloud.githubusercontent.com/assets/961966/6126444/16f6f440-b121-11e4-94ba-7501da4baa29.jpg)

**Comment by santiagopuerta** [comment]
@albertomoreno ¿HAproxy para que lo vamos a usar?

**Comment by albertomoreno** [comment]
Tenemos que esperar a que apache este funcionando.
